name: Publish to PyPI.org
on:
  push
  
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build wheels
        uses: RalfG/python-wheels-manylinux-build@v0.5.0
        with:
          python-versions: 'cp38-cp38 cp39-cp39'
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}